### Create user
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "Matheus Alexandre Barbier",
  "displayName": "matheus_aba",
  "email": "matheus.alencar0219931@gmail.com",
  "password": "password123"
}

### Get user by displayName / email
GET http://localhost:3000/user?displayName=matheus_aba21

### Get all users including deleted ones
GET http://localhost:3000/user

### Get user by db id
GET http://localhost:3000/user/cmr3t2oz20000tvl306flf1j0

### Update user passing id
PATCH http://localhost:3000/user/cmr3vq3s900004bl3tv1wxl7q
Content-Type: application/json

{
  "displayName": "matheus_aba212"
}


### Soft delete user by id
DELETE http://localhost:3000/user/cmr3vq3s900004bl3tv1wxl7q


### Login 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "matheus.alencar02199@gmail.com",
  "password": "Matheus2106"
}


### Get current user data
GET http://localhost:3000/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbXIzdDJvejIwMDAwdHZsMzA2ZmxmMWowIiwiZGlzcGxheU5hbWUiOiJtYXRoZXVzX2FiYTIxIiwicm9sZSI6IlVTRVIiLCJlbWFpbCI6Im1hdGhldXMuYWxlbmNhcjAyMTk5QGdtYWlsLmNvbSIsImlhdCI6MTc4MzAyNDQ1MiwiZXhwIjoxNzgzNjI5MjUyfQ.ucX4OORAJ4XBseAuqNhXAvg_D4MuS6BH2TQenmPDQuE

